### ISSUE TITLE
Implement RESTful data store in place of SQLite

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#391]
SS will store most data in a cache using GET/SET but it should also ask an external application to write the cache contents to persistent storage.

This persistent storage may be a database such as Mongo or just flat JSON files. Probably the latter at first as it's simpler.

At first, it will just be a cache so redis-fallover will mean data loss but that's fine for the testing phase.

Database data, in order of priority. Ticks indicate dedicated issues exist.
- [x] sss\core\player\accounts.pwn:
- [x] sss\core\admin\core.pwn:
- [x] sss\core\admin\ban.pwn:
- [x] sss\core\admin\report.pwn:
- [x] sss\core\admin\bug-report.pwn:
- [x] sss\core\player\whitelist.pwn:
- [x] sss\core\player\aliases.pwn:
- [x] sss\core\player\gpci-log.pwn:
- [x] sss\core\player\ipv4-log.pwn:
- [x] sss\core\admin\detfield.pwn:

(Note: `gpci-log`, `ipv4-log` and `aliases` will be merged into a single `history` module)

**Comment by Southclaws** [comment]
Plans for all SQL based systems have been made in their respective issue pages now.

The remaining systems that used modio for storage will remain as modio-based storage for now as it's simple, doesn't cause any of the issues SQLite was and seems to work fine for now. In the future they will likely be upgraded as viewing MongoDB is much easier than reading a propietary format that I wrote!

This issue will remain open until a milestone is created for future integrations.
