### ISSUE TITLE
Move remaining persistent data to RESTful API

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#456]
Player data, in order of priority:
- [ ] core/vehicle/player-vehicle.pwn:
- [ ] core/weapon/damage-core.pwn:
- [ ] core/player/language.pwn:
- [ ] core/char/aim-shout.pwn:
- [ ] core/char/drugs.pwn:
- [ ] core/char/infection.pwn:
- [ ] core/char/travel-stats.pwn:
- [ ] core/char/skills.pwn:

Other:
- [ ] Generic Item IO
  - [ ] Safeboxes
  - [ ] Tents
  - [ ] Plot Poles
- [ ] Anything else I've missed

**Comment by melh10000** [comment]
southlaws me ajuda ta dando esse erro na minha gm scarvenge

C:\Users\joelmalima\Desktop\ScavengeSurvive-1759\pawno\include\YSI\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(251) : error 076: syntax error in the expression, or invalid function call
C:\Users\joelmalima\Desktop\ScavengeSurvive-1759\pawno\include\YSI\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(251) : error 029: invalid expression, assumed zero
C:\Users\joelmalima\Desktop\ScavengeSurvive-1759\pawno\include\YSI\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(251) : error 035: argument type mismatch (argument 1)
C:\Users\joelmalima\Desktop\ScavengeSurvive-1759\pawno\include\YSI\..\YSI_Core\..\YSI_Coding\y_va/impl.inc(251) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase


4 Errors.

**Comment by Southclaws** [comment]
@melh10000 please don't post unrelated compiler output here. YSI is on every line of that log so you should probably go ask the YSI maintainers about it.

**Comment by Y-Less** [comment]
And (since I watch this project), please include the line itself - YSI changes a lot, so line numbers are less useful than you might expect.  Make sure amx_assembly is up-to-date.

@Southclaws can delete these if he feels they are too offtopic.  As he says, in the future post here:

https://github.com/Misiur/YSI-Includes/issues
